Ramsay t/translation efficiency 2
IntersectMBO/plutus pull request #6746
Opened 2024-12-12 15:09 UTC by ramsay-t

I broke the other PR :( sorry. This one should be properly signed and mergable?

2025-02-14 13:24 UTC, ana-pantilie commented
@ramsay-t let me know when this is ready for review again.

2025-02-14 13:24 UTC, ana-pantilie reviewed
@ramsay-t let me know when this is ready for review again.

2025-02-22 08:10 UTC, ramsay-t commented
@ana-pantilie @Unisay I've done some fairly horrible things with our golden testing functions but it seems to work :) There are two examples - one currently certifying and one not - with a simple process to add more. 

Yes, technically a test of the certifier ought to not invoke the optimiser and should use the AST stacks as input, rather than UPLC and calling the optimiser, but that would be really annoying to serialise and store. I would argue that if we change the optimiser enough to change the code it produces then we probably should re-read the certifier tests at least quickly to make we haven't changed anything the certifier *should* care about.

2025-02-24 09:11 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +    , testGroup "failing certification"  $ makeTestTree failingTests
It's good that we can run tests on CI now, but an important aspect of testing is communicating intent: why do we expect the `len` test to fail?

2025-02-24 09:15 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +    , testGroup "failing certification"  $ makeTestTree failingTests
As the comment above the definition on line 48 says: they "fail" in the sense that the certifier says "no" (currently). We will need to look into why that is, but you explicitly asked me to include this so we know the semantics aren't changed (until we do change them).

2025-02-24 14:56 UTC, Unisay commented
Please re-format the `plutus-executables/test/certifier/Spec.hs` with fourmolu

2025-02-24 15:06 UTC, Unisay commented on plutus-executables/test/certifier/Spec.hs
> +{-# LANGUAGE OverloadedStrings #-}
This pragma is likely not needed as the language extension is already switched on by default in  the cabal file.

2025-02-24 15:08 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +    , testGroup "failing certification"  $ makeTestTree failingTests
Usually you want to add tests which actually behave the way you expect them to. So this failing test should be transformed into a succeeding test, and commented out until it's fixed.

2025-02-24 15:10 UTC, ana-pantilie commented
Can you add the rest of the tests we were using to check the certifier manually? Like the ones generated by the `uplc` executable (factorial, fibonacci etc.).

2025-02-24 17:35 UTC, effectfully approved these changes
Fine by me, but to repeat my previous point I currently do not believe this is the right solution long-term despite it making things faster short-term. More on that [here](https://github.com/IntersectMBO/plutus/pull/6713#issuecomment-2505645505).

2025-02-25 06:50 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +    , testGroup "failing certification"  $ makeTestTree failingTests
Perhaps "failing" is the wrong name - we want some tests that _don't_ certify. Otherwise we are just demonstrating that the certifier says "yes", and not that it actually checks things. I'm not sure what English word you would prefer to "failing" in that case? Rejected, or Negative?

2025-02-25 09:01 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +{- | The tests in this file run tests of the uplc certifier. Various unoptimised UPLC is
...this is 89?

I'm all for the classic 80 character limit if you'd prefer, but then lets set the github commit hook to enforce that.

2025-02-25 09:24 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +    , testGroup "failing certification"  $ makeTestTree failingTests
Yes, I know really we should have tests that we _intend_ to be rejected, but I was hoping to avoid turning this into a solid week of test engineering ;) I shall do that though...

2025-02-25 09:26 UTC, ramsay-t commented
> Can you add the rest of the tests we were using to check the certifier manually? Like the ones generated by the `uplc` executable (factorial, fibonacci etc.).

The problem is they are randomly generated, so we can't do them as "golden" tests. Then we would have to decide what we are testing? Do we assume they all certify? Are we defining that as the last line of the response being "The compilation was successfully certified." - or do we actually set the exit code properly in the executable when certification fails?

2025-02-25 10:28 UTC, ana-pantilie commented
@ramsay-t 

> The problem is they are randomly generated, so we can't do them as "golden" tests. 

How are they randomly generated? They're just UPLC programs, we can add the UPLC code as you have with the other tests you added here. 

> Then we would have to decide what we are testing? Do we assume they all certify? 

It doesn't make sense to have integration tests which are expected to fail. That would mean that either the compiler or the certifier is broken in some way.

> Are we defining that as the last line of the response being "The compilation was successfully certified." - or do we actually set the exit code properly in the executable when certification fails?

I think just checking the text is fine for now, we can improve that in the future.

2025-02-25 19:18 UTC, ramsay-t commented on plutus-executables/plutus-executables.cabal
@effectfully this appears to have changed nothing in the CI :( perhaps you meant something different?

2025-02-25 21:11 UTC, effectfully commented on plutus-executables/plutus-executables.cabal
I think you need to import it, like it's done in this file with `os-support`.

2025-02-26 06:50 UTC, ramsay-t commented on plutus-executables/plutus-executables.cabal
Well, that fails _fast_ at least :)

2025-02-26 17:48 UTC, ana-pantilie requested changes

2025-02-26 17:48 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +  ]
It doesn't make sense to keep this. It's dead code.

2025-02-26 17:48 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +  -- , len
At least add a comment describing why this test is not enabled.

2025-02-26 17:48 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
Can you please add the other tests as well as I asked? That should be very quick. I would normally be ok with you adding these in a separate PR, but since you decided to combine the testing framework with changes to the decision procedures as well, I will have to insist that you show that the changes to the decision procedures do not break any of the tests we have been running manually until now.

2025-02-26 18:41 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +  ]
No it isn't its called on line 104 😸

2025-02-26 18:42 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
They are in the makeExample list....? Since they are generated from the executable it made more sense to let it generate fresh versions each time and certify those. We could include hardcoded instances or each of them, but the fresh ones are maybe more interesting?

2025-02-26 19:36 UTC, ana-pantilie approved these changes

2025-02-27 00:23 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
Except: why do these never trigger the bug that the short “len” example triggers? They are probably already optimised and so are just returning an ID change all the time…. If we can make them unoptimised then they will be more useful but will currently fail (possibly randomly?)

2025-02-27 12:10 UTC, ana-pantilie commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
I remember that the `uplc` examples are unoptimised. If I printed the `factorial` or whatever script, I remember seeing `force ... delays` that could definitely be reduced.

2025-02-27 12:16 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
Looking at the generated certificates, there does seem to be _some_ changes happening, so these are meaningful tests - although they might be more meaningful if we used the plc examples and then fed those in so there was more work happening...

2025-02-27 12:19 UTC, ramsay-t commented on plutus-executables/test/certifier/Spec.hs
> +  [ "inc"
I think we were typing at the same time :) These are fine for now, although I could spend ages improving them!

2025-03-04 11:24 UTC, merged