Add docs on data-backed ScriptContext
IntersectMBO/plutus pull request #6759
Opened 2024-12-20 16:10 UTC by ana-pantilie

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense
    - [ ] Key commits have useful messages
    - [ ] Changelog fragments have been written (if appropriate)
    - [ ] Relevant tickets are mentioned in commit messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting master unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] Reviewer requested

2024-12-20 16:38 UTC, zliu41 requested changes
The documentation should follow the format of having one sentence per line.

As an initial thought, here are some things that should be mentioned - I may have more to add later.
- When extracting fields from ScriptContext (and in general all Data-encoded types), don't use field accessors, but use record patterns to extract all needed fields at the beginning (and briefly explain why).
- If your data type includes fields that are lists or maps and you want to wrap it in `asData`, make sure to use the Data versions of map and list.

2024-12-23 11:12 UTC, ana-pantilie commented
> don't use field accessors, but use record patterns to extract all needed fields at the beginning (and briefly explain why)

@zliu41 I'm not sure I understand why. As far as I could see, the record patterns are just syntactic sugar over the field accessor functions. I need to look at the way GHC transforms record patterns into Haskell Core again, but I never got the impression the record pattern syntax makes any difference at that level.

I assume you're not referring to the behavior you discovered with matching on pattern synonyms like `ScriptContext _ _ _`, that the PIR contains some tuple, right?

2024-12-23 15:15 UTC, zliu41 commented
Using field accessors leads to repetitive computation. Extracting the third field is `head . tail . tail . snd . unsafeDataAsConstr`. Later, extracting the fourth field involves the same computation, but one more `tail`. You must rely on CSE to reduce the repetition, but it is unreliable.

2024-12-23 15:18 UTC, zliu41 commented
By the way see this slack thread: https://input-output-rnd.slack.com/archives/G01EE4NQ9U0/p1728897590920289

2025-01-06 17:43 UTC, zliu41 approved these changes
:+1:

2025-01-06 17:43 UTC, merged